# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nuoe397vCD1H2TWZGAl_A2mRwx043_3U
"""

import streamlit as st
import joblib
import numpy as np
import os

# -------------------------------
# Load Model
# -------------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
model_path = os.path.join(BASE_DIR, "logistic_model.pkl")
model = joblib.load(model_path)

st.title("Diabetes Prediction App")
st.write("Logistic Regression Model Deployment")

# -------------------------------
# User Inputs (MATCH TRAINING FEATURES)
# -------------------------------

pregnancies = st.number_input("Pregnancies", min_value=0, max_value=20, value=1)
glucose = st.number_input("Glucose", min_value=0, max_value=200, value=120)
blood_pressure = st.number_input("Blood Pressure", min_value=0, max_value=150, value=70)
skin_thickness = st.number_input("Skin Thickness", min_value=0, max_value=100, value=20)
insulin = st.number_input("Insulin", min_value=0, max_value=900, value=80)
bmi = st.number_input("BMI", min_value=0.0, max_value=70.0, value=25.0)
diabetes_pedigree = st.number_input("Diabetes Pedigree Function", min_value=0.0, max_value=3.0, value=0.5)
age = st.number_input("Age", min_value=1, max_value=100, value=30)

# -------------------------------
# Prediction
# -------------------------------

input_data = np.array([[pregnancies, glucose, blood_pressure, skin_thickness,
                        insulin, bmi, diabetes_pedigree, age]])

if st.button("Predict"):
    prediction = model.predict(input_data)[0]
    probability = model.predict_proba(input_data)[0][1]

    if prediction == 1:
        st.error(f"High chance of Diabetes ❌ (Probability: {probability:.2f})")
    else:
        st.success(f"Low chance of Diabetes ✅ (Probability: {probability:.2f})")