# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nuoe397vCD1H2TWZGAl_A2mRwx043_3U
"""

import streamlit as st
import joblib
import numpy as np

# -------------------------------
# Load trained model
# -------------------------------
model = joblib.load("logistic_model.pkl")

st.title("Diabetes Prediction App")
st.write("Predict whether a patient has diabetes or not based on features.")

# -------------------------------
# User Inputs
# -------------------------------
pregnancies = st.number_input("Pregnancies", min_value=0, value=0)
glucose = st.number_input("Glucose Level", min_value=0, value=120)
blood_pressure = st.number_input("Blood Pressure", min_value=0, value=70)
bmi = st.number_input("BMI", min_value=0.0, value=25.0)
dpf = st.number_input("Diabetes Pedigree Function", min_value=0.0, value=0.5)
age = st.number_input("Age", min_value=0, value=30)

# -------------------------------
# Prepare input for prediction
# -------------------------------
input_data = np.array([[pregnancies, glucose, blood_pressure, bmi, dpf, age]])

# -------------------------------
# Prediction
# -------------------------------
if st.button("Predict"):
    # Class prediction: 0 = Does Not Have Diabetes, 1 = Has Diabetes
    prediction = model.predict(input_data)[0]

    if prediction == 1:
        st.error("Has Diabetes ❌")
    else:
        st.success("Does NOT Have Diabetes ✅")