# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nuoe397vCD1H2TWZGAl_A2mRwx043_3U
"""

import streamlit as st
import joblib
import numpy as np

# Load trained model
model = joblib.load("logistic_model.pkl")

st.title("Survival Prediction App (Logistic Regression)")

st.write("Enter passenger details to predict survival probability")

# User Inputs
age = st.number_input("Age", min_value=0, max_value=100, value=30)
fare = st.number_input("Fare", min_value=0.0, value=50.0)
sex = st.selectbox("Sex", ["Male", "Female"])
pclass = st.selectbox("Passenger Class", [1, 2, 3])

# Encode inputs
sex_encoded = 1 if sex == "Male" else 0

input_data = np.array([[pclass, sex_encoded, age, fare]])

# Prediction
if st.button("Predict"):
    prediction = model.predict(input_data)
    probability = model.predict_proba(input_data)[0][1]

    if prediction[0] == 1:
        st.success(f"Passenger is likely to Survive (Probability: {probability:.2f})")
    else:
        st.error(f"Passenger is likely NOT to Survive (Probability: {probability:.2f})")