# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nuoe397vCD1H2TWZGAl_A2mRwx043_3U
"""

import streamlit as st
import joblib
import numpy as np

# -------------------------------
# Load trained model
# -------------------------------
model = joblib.load("logistic_model.pkl")

st.title("Diabetes Risk Prediction App")
st.write("Predict the risk of Diabetes based on patient features.")

# -------------------------------
# User Inputs
# -------------------------------
pregnancies = st.number_input("Pregnancies", min_value=0, value=0)
glucose = st.number_input("Glucose Level", min_value=0, value=120)
blood_pressure = st.number_input("Blood Pressure", min_value=0, value=70)
skin_thickness = st.number_input("Skin Thickness", min_value=0, value=20)
insulin = st.number_input("Insulin Level", min_value=0, value=79)
bmi = st.number_input("BMI", min_value=0.0, value=25.0)
dpf = st.number_input("Diabetes Pedigree Function", min_value=0.0, value=0.5)
age = st.number_input("Age", min_value=0, value=30)

# -------------------------------
# Prepare input for prediction
# -------------------------------
input_data = np.array([[pregnancies, glucose, blood_pressure, skin_thickness,
                        insulin, bmi, dpf, age]])

# -------------------------------
# Prediction
# -------------------------------
if st.button("Predict"):
    # Class prediction (0 = No Diabetes, 1 = Diabetes)
    prediction = model.predict(input_data)[0]

    # Probability of having diabetes
    probability = model.predict_proba(input_data)[0][1]

    if prediction == 1:
        st.error(f"High chance of Diabetes ❌ (Probability: {probability:.2f})")
    else:
        st.success(f"Low chance of Diabetes ✅ (Probability: {probability:.2f})")